### ISSUE TITLE
Automate the release on OBS

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/osc-tiny#138]
The steps to submit new releases for openSUSE Tumbleweed are simple and can be fully automated:

1. Branch package from Factory
2. Replace the version string in the `.spec` file
3. Replace the source tarball
4. Add the release notes to the `.changes` file
5. Commit/Upload the changes
6. Submit a request

These steps could be performed in the `publish` workflow after the package is uploaded to PyPI

**Comment by der-gabe** [comment]
I like the idea of automating the roll-out of `osc-tiny` releases on Open Build Service and we got certainly go the route outlined here with that.

But I wonder whether it wouldn't be even better to use a service on the Build Service side that fetches the sources from here, or PyPI, and a webhook to trigger that service run...

What do you think?

**Comment by crazyscientist** [comment]
> se a service on the Build Service side that fetches the sources from here, or PyPI, and a webhook to trigger that service run

That would be really neat. I tried that approach when I first submitted osc-tiny and the submission was rejected. We certainly can check, whether the relevant policy has changed in the meantime.
