### ISSUE TITLE
`Osc.projects.get_meta` always returns the latest revision regardless of the `rev` parameter

### ISSUE THREAD

**Issue by oSoMoN** [SUSE/osc-tiny#146]
Following up on #145, I've noticed that the version of the meta returned by `Osc.projects.get_meta` is always the latest revision, regardless of the value of the `rev` parameter:

```python
from lxml.etree import tostring
from osctiny import Osc

iosc = Osc(url='https://api.suse.de')
meta8 = iosc.projects.get_meta('SUSE:Maintenance:30953', rev=8)
meta9 = iosc.projects.get_meta('SUSE:Maintenance:30953', rev=9)
assert tostring(meta8) != tostring(meta9)  # this raises an AssertionError
```

However if I append `/_project` to the project name being queried, I'm getting the expected values for the meta of the project:

```python
meta8 = iosc.projects.get_meta('SUSE:Maintenance:30953/_project', rev=8)
meta9 = iosc.projects.get_meta('SUSE:Maintenance:30953/_project', rev=9)
assert tostring(meta8) != tostring(meta9)  # OK
```

I believe `get_meta` should be appending that `/_project` suffix when querying the build service for the meta.

**Comment by crazyscientist** [comment]
Once more, a very nice example of the messiness of the OBS API :slightly_frowning_face: 

Apparently, `/source/{project}/_meta` is only a shortcut to the current version of the meta, but via `/source/{project}/_project/_meta` we get access to all the revisions.
