### ISSUE TITLE
Osc.staging.set_status_report() always returns False

### ISSUE THREAD

**Issue by oSoMoN** [SUSE/osc-tiny#158]
`Osc.staging.set_status_report()` always returns `False` because [the implementation](https://github.com/SUSE/osc-tiny/blob/master/osctiny/extensions/staging.py#L381) expects the parsed response object to have a "code" attribute with a value of "ok".

In my tests, SUSE's internal build system returns a check object that doesn't have a "code" attribute. This looks like:

```xml
<check name="foo" required="true">
  <state>success</state>
  <short_description>check was successful</short_description>
  <url>http://example.org/</url>
</check>
```

**Comment by crazyscientist** [comment]
You gotta love the consistency in the API design :joy:
